In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder,KBinsDiscretizer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [4]:
df=pd.read_csv("/content/adult.csv")

In [5]:
features=['age','education.num','marital.status','capital.gain','capital.loss','hours.per.week']
X=df[features]
y=df['income']

In [6]:
(X=='?').sum()

age               0
education.num     0
marital.status    0
capital.gain      0
capital.loss      0
hours.per.week    0
dtype: int64

In [7]:
(y=='?').sum()

np.int64(0)

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
num_cols=['age','capital.gain','capital.loss','hours.per.week']
cat_cols=['marital.status']
passthrough_cols=['education.num']

preprocessor =ColumnTransformer(
    transformers=[
        ('num',KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile'),num_cols),
        ('cat',OrdinalEncoder(),cat_cols),
        ('pass','passthrough',passthrough_cols)
    ]
)

In [ ]:
preprocessor=ColumnTransformer(
    transformer=[
        ('num',kBinsDiscretizer(n_bins=5,encode='ordinal',statergy='quantile'),num_cols),
        ('cat',OridinalEncoder(),cat_cols),
        ('pass','passthrough',passthrough_cols)
    ]
)

X_procssor=preprocessor.transform(X_train)

In [10]:
X_train_processed=preprocessor.fit_transform(X_train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:306: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:306: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:306: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(

In [11]:
X_test_processed = preprocessor.transform(X_test)

In [12]:
from sklearn.tree import DecisionTreeClassifier

cart_model = DecisionTreeClassifier(criterion='gini', random_state=42)
cart_model.fit(X_train_processed, y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
from sklearn.tree import DecisionTreeClassifier

id3_model = DecisionTreeClassifier(criterion='entropy', random_state=42)
id3_model.fit(X_train_processed, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [14]:
from sklearn.naive_bayes import CategoricalNB

nb_model = CategoricalNB()
nb_model.fit(X_train_processed, y_train)

CategoricalNB()

In [15]:
from sklearn.metrics import accuracy_score
y_pred_cart = cart_model.predict(X_test_processed)
accuracy_score(y_test, y_pred_cart)

0.8237281195618794

In [16]:
y_pred_nb = nb_model.predict(X_test_processed)
accuracy_score(y_test, y_pred_nb)

0.8240352134302386

In [17]:
y_pred_id3 = id3_model.predict(X_test_processed)
accuracy_score(y_test, y_pred_id3)

0.8237281195618794

In [18]:
cart_accuracy = accuracy_score(y_test, y_pred_cart)
id3_accuracy = accuracy_score(y_test, y_pred_id3)
nb_accuracy = accuracy_score(y_test, y_pred_nb)


comparison_df = pd.DataFrame({
    'Model': ['CART', 'ID3', 'Naive Bayes'],
    'Accuracy': [cart_accuracy, id3_accuracy, nb_accuracy]
})

display(comparison_df.sort_values(by='Accuracy', ascending=False))

         Model  Accuracy
2  Naive Bayes  0.824035
0         CART  0.823728
1          ID3  0.823728