In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [3]:
df=pd.read_csv('Raisin.csv')

In [4]:
df.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,Kecimen
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,Kecimen
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,Kecimen

In [5]:
X=df.drop('Class',axis=1)
y=df['Class']

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [8]:
pca=PCA(n_components=4)
X_pca=pca.fit_transform(X_scaled)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.3)

In [12]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8814814814814815

In [17]:
# !pip install minisom
from minisom import MiniSom
df=pd.read_csv("aqi.csv")

X=df[['pm25','pm10','co','o3']]

In [18]:
X.head()

         pm25        pm10        co         o3
0   99.868566  147.103280  0.729754  46.487946
1  143.168513  208.517207  0.660975  43.014054
2   89.678491  101.412886  0.496151  54.713710
3   43.679037   65.432963  0.820258  28.628777
4   58.224691  110.443143  0.619808  45.624594

In [19]:
X=(X-X.mean())/X.std()
som=MiniSom(x=5,y=5,input_len=4,sigma=1.0,learning_rate=0.5)

In [20]:
som.train_random(X.values,100)

In [22]:
win_map=[som.winner(x) for x in X.values]

In [23]:
print(win_map)

[(np.int64(4), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(4)), (np.int64(3), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(3), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(4)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(3)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(4)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(1), np.int64(4)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(0)), (np.int64(1), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(3)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(3)), (np.int64(3), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(1), np.int64(3)), (np.int64(2), np.int64(3)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(4)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(4)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(4)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(4), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(0)), (np.int64(2), np.int64(4)), (np.int64(4), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(3), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(4)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(2), np.int64(0)), (np.int64(4), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(3)), (np.int64(4), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(3)), (np.int64(2), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(3)), (np.int64(0), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(1), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(4), np.int64(4)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(0)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(3), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(1), np.int64(0)), (np.int