In [109]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
!pip install svm
from sklearn.svm import SVC

Requirement already satisfied: svm in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (0.1.0)
Requirement already satisfied: requests in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from svm) (2.32.5)
Requirement already satisfied: colorama in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from svm) (0.4.6)
Requirement already satisfied: xmltodict in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from svm) (1.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from requests->svm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from requests->svm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from requests->svm) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\symdr\appdata\local\programs\python\python311\lib\site-packages (from requests->svm) (2026.1.4)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [110]:
train=pd.read_csv("thyroid-diag/thyroid-diag/sick.data",header=None)

In [111]:
test=pd.read_csv("thyroid-diag/thyroid-diag/sick.test")

In [112]:
columns = [
'age','sex','on_thyroxine','query_on_thyroxine','on_antithyroid_medication',
'sick_flag','pregnant','thyroid_surgery','I131_treatment','query_hypothyroid',
'query_hyperthyroid','lithium','goitre','tumor','hypopituitary','psych',
'TSH_measured','TSH','T3_measured','T3','TT4_measured','TT4',
'T4U_measured','T4U','FTI_measured','FTI','TBG_measured','TBG',
'referral_source','target'
]

train.columns = columns
test.columns = columns

In [113]:
train.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick_flag,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,target
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,negative.|3733
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,negative.|1442
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,negative.|2965
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,negative.|806
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,negative.|2807

In [114]:
train.drop(columns=['TBG','TBG_measured'])
test.drop(columns=['TBG','TBG_measured'])

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick_flag,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,referral_source,target
0,63,M,f,f,f,f,f,f,f,f,...,t,2.5,t,108,t,0.96,t,113,SVI,negative.|2059
1,25,F,f,f,f,f,f,f,f,f,...,t,2.4,t,61,t,0.82,t,75,SVHD,negative.|399
2,53,F,f,f,f,f,f,f,f,t,...,t,2.1,t,145,t,1.03,t,141,other,negative.|1911
3,92,F,f,f,f,f,f,f,f,f,...,t,1.3,t,120,t,0.84,t,143,SVI,negative.|487
4,67,M,f,f,f,f,f,f,f,t,...,f,?,t,84,t,0.83,t,101,other,negative.|1234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,30,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,f,?,other,negative.|2924
967,68,F,f,f,f,f,f,f,f,f,...,t,2.1,t,124,t,1.08,t,114,SVI,negative.|974
968,74,F,f,f,f,f,f,f,f,f,...,t,1.8,t,112,t,1.07,t,105,other,negative.|1493
969,72,M,f,f,f,f,f,f,f,f,...,t,2,t,82,t,0.94,t,87,SVI,negative.|252
970,64,F,f,f,f,f,f,f,f,f,...,t,2.2,t,99,t,1.07,t,92,other,negative.|2008

In [115]:
train.replace('?',np.nan,inplace=True)
test.replace('?', np.nan,inplace=True)

C:\Users\symdr\AppData\Local\Temp\ipykernel_24072\599628613.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train.replace('?',np.nan,inplace=True)
C:\Users\symdr\AppData\Local\Temp\ipykernel_24072\599628613.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test.replace('?', np.nan,inplace=True)

In [116]:
train['target']=train['target'].str.split('.').str[0]
test['target']=test['target'].str.split('.').str[0]

In [117]:
numeric_cols = ['age','TSH','T3','TT4','T4U','FTI']

for col in numeric_cols:
    train[col] = pd.to_numeric(train[col], errors='coerce')
    test[col] = pd.to_numeric(test[col], errors='coerce')

In [118]:
for col in numeric_cols:
    train[col] = train[col].fillna(train[col].median())
    test[col] = test[col].fillna(test[col].median())

In [119]:
categorical_cols = train.select_dtypes(include='object').columns

for col in categorical_cols:
    train[col] = train[col].fillna(train[col].mode()[0])
    test[col] = test[col].fillna(test[col].mode()[0])

In [120]:
X=pd.get_dummies(train)
y=pd.get_dummies(test)

In [121]:
import sklearn
dir(sklearn.preprocessing)

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'OrdinalEncoder',
 'PolynomialFeatures',
 'PowerTransformer',
 'QuantileTransformer',
 'RobustScaler',
 'SplineTransformer',
 'StandardScaler',
 'TargetEncoder',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csr_polynomial_expansion',
 '_data',
 '_discretization',
 '_encoders',
 '_function_transformer',
 '_label',
 '_polynomial',
 '_target_encoder',
 '_target_encoder_fast',
 'add_dummy_feature',
 'binarize',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'power_transform',
 'quantile_transform',
 'robust_scale',
 'scale']

In [122]:
le = LabelEncoder()

for col in train.columns:
    if train[col].dtype == 'object':
        train[col] = le.fit_transform(train[col])
        test[col] = le.transform(test[col])

In [123]:
X_train = train.drop('target', axis=1)
y_train = train['target']

X_test = test.drop('target', axis=1)
y_test = test['target']

In [124]:

X=X.drop(columns=['TBG'])

In [125]:
X.isna().sum()

age                            0
TSH                            0
T3                             0
TT4                            0
T4U                            0
FTI                            0
sex_F                          0
sex_M                          0
on_thyroxine_f                 0
on_thyroxine_t                 0
query_on_thyroxine_f           0
query_on_thyroxine_t           0
on_antithyroid_medication_f    0
on_antithyroid_medication_t    0
sick_flag_f                    0
sick_flag_t                    0
pregnant_f                     0
pregnant_t                     0
thyroid_surgery_f              0
thyroid_surgery_t              0
I131_treatment_f               0
I131_treatment_t               0
query_hypothyroid_f            0
query_hypothyroid_t            0
query_hyperthyroid_f           0
query_hyperthyroid_t           0
lithium_f                      0
lithium_t                      0
goitre_f                       0
goitre_t                       0
tumor_f                        0
tumor_t                        0
hypopituitary_f                0
hypopituitary_t                0
psych_f                        0
psych_t                        0
TSH_measured_f                 0
TSH_measured_t                 0
T3_measured_f                  0
T3_measured_t                  0
TT4_measured_f                 0
TT4_measured_t                 0
T4U_measured_f                 0
T4U_measured_t                 0
FTI_measured_f                 0
FTI_measured_t                 0
TBG_measured_f                 0
referral_source_STMW           0
referral_source_SVHC           0
referral_source_SVHD           0
referral_source_SVI            0
referral_source_other          0
target_negative                0
target_sick                    0
dtype: int64

In [127]:
from sklearn.feature_selection import chi2
chi_scores,p_values=chi2(X_train,y_train)

ValueError: Input contains NaN.

In [ ]:
scaler=StandardScaler()

X_scale=scaler.fit_transform(X)
X_test=scaler.fit(test)

c:\Users\symdr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\extmath.py:1144: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
c:\Users\symdr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\extmath.py:1149: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
c:\Users\symdr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\extmath.py:1169: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

ValueError: could not convert string to float: 'M'